### ISSUE TITLE
[BUG] segmentation fault

### ISSUE THREAD

**Issue by ayoubelmhamdi** [gtk-rs/gtk4-rs#1106]
- gdb
```
[New Thread 0x7ffff49ff640 (LWP 5715)]
[New Thread 0x7fffeffff640 (LWP 5716)]
[Detaching after fork from child process 5717]
[New Thread 0x7fffef7fe640 (LWP 5718)]
[Thread 0x7ffff49ff640 (LWP 5715) exited]
[New Thread 0x7fffeeffd640 (LWP 5719)]
[New Thread 0x7ffff49ff640 (LWP 5730)]
[Thread 0x7ffff49ff640 (LWP 5730) exited]
[New Thread 0x7ffff49ff640 (LWP 5736)]
[New Thread 0x7fffed3ff640 (LWP 5737)]
[New Thread 0x7fffecabd640 (LWP 5738)]
[New Thread 0x7fffe65ff640 (LWP 5739)]
[New Thread 0x7fffe5dfe640 (LWP 5740)]

Thread 1 "simple_manual" received signal SIGSEGV, Segmentation fault.
0x00007fffe7474ab8 in ?? () from /usr/lib64/dri/crocus_dri.so
```
- `RUST_BACKTRACE=full`
compile without any error
- System
  - void linux : kernel 5.18.17_1
  - gcc10.2.1 20201203
  - cargo 1.62.1 (a748cf5a3 2022-06-08)
  - pkg-config --modversion gtk4 : 4.6.6
 
# UPDATE 1
I try to compile the [hello world](https://gtk-rs.org/gtk4-rs/git/book/hello_world.html)
Cargo.toml
```toml
[package]
name = "gtk4-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4.8", package = "gtk4", features = ["v4_6"]}
```
src/main.rs
```rust
use gtk::prelude::*;
use gtk::Application;

const APP_ID: &str = "org.gtk_rs.HelloWorld1";

fn main() {
    // Create a new application
    let app = Application::builder().application_id(APP_ID).build();

    // Run the application
    app.run();
}
```

# UPDATE 2
the code that causes the problem is
```rust
unsafe { 
    ffi::g_application_run(self.as_ref().to_glib_none().0, argc, argv.to_glib_none().0) 
}
```
