### ISSUE TITLE
[HELP] app menubar not showing, "Don't know how to handle this item"

### ISSUE THREAD

**Issue by mikedilger** [gtk-rs/gtk4-rs#1221]
I'm trying to simply show a basic application menubar.  I've spent too many hours on this, reading through gtk/gio rust documentation and searching google for examples, cloning and searching source code... and I'm still not getting anywhere so I'm opening this help request.

Here is the Cargo.toml:
````toml
[package]
name = "gtk-sample-menus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { package = "gtk4", version="0.5", features = [ "v4_8" ] }
````

Here is main.rs:
````rust
use gtk::prelude::*;
use gtk::{Application, ApplicationWindow};
use gtk::{gio, glib};

const APP_ID: &str = "com.mikedilger.example";

fn main() {
    // Create a new application
    let app = Application::builder()
        .application_id(APP_ID)
        .build();

    // Connect signals
    app.connect_startup(startup);
    app.connect_activate(build_ui);
    app.connect_shutdown(|_| {
        println!("Shutting down.");
    });

    // Run the application
    app.run();
}

fn startup(app: &Application) {
    let quit = gio::SimpleAction::new("quit", None);
    quit.connect_activate(
        glib::clone!(@weak app => move |_action, _parameter| {
            app.quit();
        }),
    );
    app.add_action(&quit);

    let about = gio::SimpleAction::new("about", None);
    about.connect_activate(|_,_| {
        println!("About was pressed");
    });
    app.add_action(&about);

    // Create a menu
    let main_menu = gio::Menu::new();

    let quit_menu = gio::MenuItem::new(Some("Quit"), Some("app.quit"));
    main_menu.append_item(&quit_menu);

    let about_menu = gio::MenuItem::new(Some("About"), Some("app.about"));
    main_menu.append_item(&about_menu);

    app.set_menubar(Some(&main_menu));
}

fn build_ui(app: &Application) {
    // Create a window and set the title
    let window = ApplicationWindow::builder()
        .application(app)
        .title("Example")
        .show_menubar(true)
        .build();

    // Present window
    window.present();
}
````

The menu bar does not show.  There are two Gtk-WARNING messages reading "Don't know how to handle this item".  If I add three menus to the menu bar, then there are three Gtk-WARNING messages.

Thanks for any light you can shine.
