### ISSUE TITLE
Displaying an image with a .bmp extension leaves white stripes on the border

### ISSUE THREAD

**Issue by kolakdd** [gtk-rs/gtk4-rs#1859]
Hello. I encountered a problem displaying images with the .bmp extension

When trying to use an image using ImageReader::open I encounter a problem - Extra white stripes appear around the image in the window.

This behavior is observed only when using the .bmp extension. For example, when using the .jpg format, white stripes are not observed.
 
A piece of code to repeat:

src/main.rs

```rs
use gtk::glib;
use gtk::prelude::*;
use gtk::{Application, ApplicationWindow, Image};
use image::GenericImageView;
use image::{ImageError, ImageReader};

const APP_ID: &str = "gtk.main";

fn main() -> glib::ExitCode {
    let app = Application::builder().application_id(APP_ID).build();
    app.connect_activate(build_ui);
    app.run()
}
fn build_ui(app: &Application) {
    let img_path = "pic/icon.jpg";
    // let img_path = "pic/image.bmp";

    let img = ImageReader::open(img_path).expect("Failed to open image");
    let img = img.decode().expect("Failed to decode image");
    let (width, height) = img.dimensions();

    let pic = Image::from_file(img_path);

    pic.set_size_request(width as i32, height as i32);

    let window = ApplicationWindow::builder()
        .application(app)
        .title("flex_image")
        .default_width(width as i32)
        .default_height(height as i32)
        .resizable(false)
        .build();

    window.set_child(Some(&pic));

    pic.set_halign(gtk::Align::Start);
    pic.set_valign(gtk::Align::Start);

    window.present();
}

```

Cargo.toml
```toml
[package]
name = "image_flexer"
version = "0.1.0"
edition = "2021"

[dependencies]
ashpd = "0.9.1"
gdk-pixbuf = "0.20.4"
image = { version = "0.25.2", features = ["bmp"] }
gtk = { version = "^0.7", features = ["v4_12"], package = "gtk4" }

```
![image](https://github.com/user-attachments/assets/3ca55535-1435-40da-9ac7-4f55030e84f7)
