### ISSUE TITLE
[BUG] ColorButton activate signal never get executed

### ISSUE THREAD

**Issue by Ungedummt** [gtk-rs/gtk4-rs#958]
**Bug description**

For context:
- [gtk docs](https://docs.gtk.org/gtk4/signal.ColorButton.activate.html)
- [gtk-rs docs](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.ColorButton.html#method.connect_activate)

According to the docs this signal should be executed after the ColorButton was pressed and dialog appeares, but the debug print never shows up.

Cargo.toml:
```toml
[package]
name = "example"
version = "0.0.1"
edition = "2021"

[dependencies]
gtk = { package = "gtk4", git = "https://github.com/gtk-rs/gtk4-rs.git", features = [ "v4_2", "v4_4" ] }
```
src/main.rs:
```rust
use gtk::prelude::*;
use gtk::*;

fn main() {
    let application = Application::new(
        Some("org.test.test"),
        Default::default(),
    );
    application.connect_activate(build_ui);
    application.run();
}

fn build_ui(application: &Application) {
    let ui_src = include_str!("gtk_builder.ui");
    let builder = Builder::from_string(ui_src);

    let window: ApplicationWindow = builder.object("window").unwrap();
    window.set_application(Some(application));

    let color_button: ColorButton = builder.object("color_button").unwrap();

    color_button.connect_activate(| _ | {
        println!("foo");
    });

    window.show();
}
```
src/gtk_builder.ui:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<interface>
  <object class="GtkApplicationWindow" id="window">
    <child>
      <object class="GtkColorButton" id="color_button">
      </object>
    </child>
  </object>
</interface>
```
